---
galaxy_info:
  author: mbongowo
  description: Install and enable the Docker engine
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
