{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "online-boutique.serviceAccountName" . }}
  labels:
    {{- include "online-boutique.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
