---
- name: Converge
  hosts: all
  become: true
  vars:
    admin_user: deploy
    admin_user_shell: /bin/bash
  roles:
    - role: common
    - role: docker
    - role: webserver
    - role: firewall
