apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-dev
nameSuffix: -dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
    includeSelectors: false

# Verbose logging in dev.
patches:
  - target:
      kind: ConfigMap
      name: platform-settings
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
